services:
  # ChatBet AI API
  chatbet-ai:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CHATBET_API_BASE_URL=https://v46fnhvrjvtlrsmnismnwhdh5y0lckdl.lambda-url.us-east-1.on.aws
      - CHATBET_API_TIMEOUT=30
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - GOOGLE_AI_MODEL=gemini-1.5-flash
      - DEBUG=true
      - API_TITLE=ChatBet AI Assistant
      - API_VERSION=1.0.0
      - MAX_CONVERSATION_HISTORY=10
      - CONVERSATION_TIMEOUT=3600
    volumes:
      - ./app:/app/app  # For development - remove in production
    restart: unless-stopped
    
  # Web Client
  web-client:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./web-client:/usr/share/nginx/html
    depends_on:
      - chatbet-ai
    restart: unless-stopped